const fs=require('fs').promises;const path=require('path');const config=require('./config');const logger=require('./logger');const Utils=require('./utils');const git=require('./git');
const g1=require('./sources/g1');const tecnoblog=require('./sources/tecnoblog');const canaltech=require('./sources/canaltech');const tecmundo=require('./sources/tecmundo');const boredpanda=require('./sources/boredpanda');
class NW{constructor(){this.s=[];if(config.SOURCES.G1.enabled)this.s.push(g1);if(config.SOURCES.TECNOBLOG.enabled)this.s.push(tecnoblog);if(config.SOURCES.CANALTECH.enabled)this.s.push(canaltech);if(config.SOURCES.TECMUNDO.enabled)this.s.push(tecmundo);if(config.SOURCES.BOREDPANDA.enabled)this.s.push(boredpanda);this.slugs=new Set();this.urls=new Set();}
async init(){await logger.init();await git.init();await git.pull();await this.load();logger.info('Iniciado');}
async load(){try{const f=await fs.readdir(config.POSTS_PATH);for(const file of f){if(file.endsWith('.md')){const c=await fs.readFile(path.join(config.POSTS_PATH,file),'utf8');const s=c.match(/slug:\s*"([^"]+)"/);const u=c.match(/original_url:\s*"([^"]+)"/);const t=c.match(/title:\s*"([^"]+)"/);if(s)this.slugs.add(s[1]);if(u)this.urls.add(u[1]);if(t)this.urls.add(Utils.generateSlug(t[1]));}}}catch(e){logger.error('L',{error:e.message});}}
dup(p){return this.slugs.has(p.slug)||this.urls.has(p.original_url)||this.urls.has(Utils.generateSlug(p.title));}
async save(p){if(this.dup(p)){logger.skip('Existe: '+p.title);return false;}const fn=Utils.generateFileName(p.slug);await fs.writeFile(path.join(config.POSTS_PATH,fn),`---\ntitle: "${p.title}"\ndate: "${p.date}"\ntags: [${p.tags.map(t=>`"${t}"`).join(',')}]\nsource: "${p.source}"\noriginal_url: "${p.original_url}"\nslug: "${p.slug}"\n---\n\n${p.content}\n`,'utf8');this.slugs.add(p.slug);this.urls.add(p.original_url);logger.ok('Salvo: '+p.title);return true;}
async run(){const s=Date.now();let nv=0,pl=0,er=0;logger.info('Iniciando...');for(const src of this.s){try{const ps=await src.fetch();for(const p of ps){try{nv+=await this.save(p)?1:(pl++,0);}catch(e){logger.error('P',{error:e.message});er++;}}await Utils.sleep(1000);}catch(e){logger.error('F '+src.name,{error:e.message});er++;}}if(nv>0)await git.commitAndPush('feat: '+nv+' posts');logger.ok('Fim em '+((Date.now()-s)/1000).toFixed(1)+'s',{novos:nv,pulados:pl,erros:er});}}
new NW().init().then(()=>new NW().run()).catch(e=>{logger.error('Fatal',{error:e.message});process.exit(1);});
